# extends:
#   - airbnb-base
#   - plugin:vue/base
#   - plugin:vue/recommended
#   - plugin:vue/strongly-recommended
# plugins:
#   - vue
# env:
#   browser: true
# parserOptions:
#   ecmaVersion: 2019
# rules:
#   semi:
#     - error
#     - never
#   vue/html-closing-bracket-newline:
#     - error
#     - { singleline: never, multiline: never }
#   vue/html-indent:
#     - error
#     - 2
#     - { alignAttributesVertically: false }
#   vue/max-attributes-per-line:
#     - error
#     - { singleline: 3, multiline: { max: 3 } }
#   vue/multi-word-component-names:
#     - error
#     - ignores: ['table']
